Table "users" {
  "user_id" bigint [primary key, not null]
  "email" "character varying(50)" [default: NULL]
  "name" "character varying(50)" [default: NULL]
  "mobile" "character varying(50)" [default: NULL]
  "password" "character varying(255)" [default: NULL]
  "confirmed" boolean [not null, default: false]
  "chat_id" "character varying(50)" [default: NULL]
  Indexes {
    email [type: btree, unique, name: "users_email_idx"]
    chat_id [type: btree, unique, name: "users_chat_idx"]
  }
}

Table "users_tokens" {
  "user_id" bigint [primary key, not null]
  "token" "character varying(255)" [not null]
  Indexes {
    token [type: btree, unique, name: "uk_users_tokens_token_idx"]
  }
}

Table "sessions" {
  "session_id" bigint [primary key, not null]
  "user_id" bigint [not null]
  "session_key" "character varying(255)" [not null]
  "session_value" "character varying(255)" [not null]
  "updated" timestamp [not null, default: 'now()']
  // Indexes {
  //   session_key
  // }
}

Ref "fk_users_tokens_user":"users"."user_id" < "users_tokens"."user_id" [delete: cascade]
Ref "fk_sessions_user":"users"."user_id" < "sessions"."user_id" [delete: cascade]
